# Generated by Django 4.2.6 on 2023-10-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=220)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.IntegerField(default=0)),
                ('used_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('YANGI', 'Yangi'), ('BEKOR QILINGAN', 'Bekor Qilingan'), ('MODIRATSIYADA', 'Modiratsiya')], default='NEW', max_length=20)),
                ('office_name', models.CharField(blank=True, max_length=220)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
